M48
; DRILL file {KiCad (6.0.7)} date Wed Oct 19 20:59:45 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-19T20:59:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.4882Y-2.2441
X4.4882Y-4.5276
X6.6142Y-2.2441
X6.6142Y-4.5276
T0
M30
