#include "keymap.h"

uint8_t keymap_decode(enum hid_keyboard_keypad_usage kc) {
  switch (kc) {
  case KC_A:
    return 'a';
  case KC_B:
    return 'b';
  case KC_C:
    return 'c';
  case KC_D:
    return 'd';
  case KC_E:
    return 'e';
  case KC_F:
    return 'f';
  case KC_G:
    return 'g';
  case KC_H:
    return 'h';
  case KC_I:
    return 'i';
  case KC_J:
    return 'j';
  case KC_K:
    return 'k';
  case KC_L:
    return 'l';
  case KC_M:
    return 'm';
  case KC_N:
    return 'n';
  case KC_O:
    return 'o';
  case KC_P:
    return 'p';
  case KC_Q:
    return 'q';
  case KC_R:
    return 'r';
  case KC_S:
    return 's';
  case KC_T:
    return 't';
  case KC_U:
    return 'u';
  case KC_V:
    return 'v';
  case KC_W:
    return 'w';
  case KC_X:
    return 'x';
  case KC_Y:
    return 'y';
  case KC_Z:
    return 'z';
  case KC_0:
    return '0';
  case KC_1:
    return '1';
  case KC_2:
    return '2';
  case KC_3:
    return '3';
  case KC_4:
    return '4';
  case KC_5:
    return '5';
  case KC_6:
    return '6';
  case KC_7:
    return '7';
  case KC_8:
    return '8';
  case KC_9:
    return '9';
  case KC_ENTER:
    return '\n';
  case KC_ESCAPE: // TODO For now...
  case KC_BACKSPACE:
    return 0;
  case KC_TAB:
    return '\t';
  case KC_SPACE:
    return ' ';
  case KC_MINUS:
    return '-';
  case KC_EQUAL:
    return '=';
  case KC_LEFT_BRACKET:
    return '{';
  case KC_RIGHT_BRACKET:
    return '}';
  case KC_BACKSLASH:
    return '\\';
  case KC_NONUS_HASH: // TODO... wat...
    return 0;
  case KC_SEMICOLON:
    return ';';
  case KC_QUOTE:
    return '\'';
  case KC_GRAVE:
    return '`';
  case KC_COMMA:
    return ',';
  case KC_DOT:
    return '.';
  case KC_SLASH:
    return '/';
  case KC_CAPS_LOCK:
  case KC_F1:
  case KC_F2:
  case KC_F3:
  case KC_F4:
  case KC_F5:
  case KC_F6:
  case KC_F7:
  case KC_F8:
  case KC_F9:
  case KC_F10:
  case KC_F11:
  case KC_F12:
  case KC_PRINT_SCREEN:
  case KC_SCROLL_LOCK:
  case KC_PAUSE:
  case KC_INSERT:
  case KC_HOME:
  case KC_PAGE_UP:
  case KC_DELETE:
  case KC_END:
  case KC_PAGE_DOWN:
  case KC_RIGHT:
  case KC_LEFT:
  case KC_DOWN:
  case KC_UP:
  case KC_NUM_LOCK:
  case KC_KP_SLASH:
  case KC_KP_ASTERISK:
  case KC_KP_MINUS:
  case KC_KP_PLUS:
  case KC_KP_ENTER:
  case KC_KP_1:
  case KC_KP_2:
  case KC_KP_3:
  case KC_KP_4:
  case KC_KP_5:
  case KC_KP_6:
  case KC_KP_7:
  case KC_KP_8:
  case KC_KP_9:
  case KC_KP_0:
  case KC_KP_DOT:
  case KC_NONUS_BACKSLASH:
  case KC_APPLICATION:
  case KC_KB_POWER:
  case KC_KP_EQUAL:
  case KC_F13:
  case KC_F14:
  case KC_F15:
  case KC_F16:
  case KC_F17:
  case KC_F18:
  case KC_F19:
  case KC_F20:
  case KC_F21:
  case KC_F22:
  case KC_F23:
  case KC_F24:
  case KC_EXECUTE:
  case KC_HELP:
  case KC_MENU:
  case KC_SELECT:
  case KC_STOP:
  case KC_AGAIN:
  case KC_UNDO:
  case KC_CUT:
  case KC_COPY:
  case KC_PASTE:
  case KC_FIND:
  case KC_KB_MUTE:
  case KC_KB_VOLUME_UP:
  case KC_KB_VOLUME_DOWN:
  case KC_LOCKING_CAPS_LOCK:
  case KC_LOCKING_NUM_LOCK:
  case KC_LOCKING_SCROLL_LOCK:
  case KC_KP_COMMA:
  case KC_KP_EQUAL_AS400:
  case KC_INTERNATIONAL_1:
  case KC_INTERNATIONAL_2:
  case KC_INTERNATIONAL_3:
  case KC_INTERNATIONAL_4:
  case KC_INTERNATIONAL_5:
  case KC_INTERNATIONAL_6:
  case KC_INTERNATIONAL_7:
  case KC_INTERNATIONAL_8:
  case KC_INTERNATIONAL_9:
  case KC_LANGUAGE_1:
  case KC_LANGUAGE_2:
  case KC_LANGUAGE_3:
  case KC_LANGUAGE_4:
  case KC_LANGUAGE_5:
  case KC_LANGUAGE_6:
  case KC_LANGUAGE_7:
  case KC_LANGUAGE_8:
  case KC_LANGUAGE_9:
  case KC_ALTERNATE_ERASE:
  case KC_SYSTEM_REQUEST:
  case KC_CANCEL:
  case KC_CLEAR:
  case KC_PRIOR:
  case KC_RETURN:
  case KC_SEPARATOR:
  case KC_OUT:
  case KC_OPER:
  case KC_CLEAR_AGAIN:
  case KC_CRSEL:
  case KC_EXSEL:
  case KC_LEFT_CTRL:
  case KC_LEFT_SHIFT:
  case KC_LEFT_ALT:
  case KC_LEFT_GUI:
  case KC_RIGHT_CTRL:
  case KC_RIGHT_SHIFT:
  case KC_RIGHT_ALT:
  case KC_RIGHT_GUI:
  default:
    return 0;
  }
}
